version: "3"

services: 
  nginx:
    image: nginx
    volumes:
      - ${LETSENCRYPT:-./.certificates}:/etc/letsencrypt
      - ./www/:/var/www
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
      - 8080:8080
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    environment: 
      - PORT=3000
