version: "3"

services: 
  web:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './www:/www'
      - '/etc/letsencrypt:/etc/letsencrypt'
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'
