version: "3"

services: 
  nginx:
    image: nginx
    volumes:
      - ./.letsencrypt:/etc/letsencrypt
      - ./www/:/var/www
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
