version: "3"

services: 
  web:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './www:/www'
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot