name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .ssh
        run: |
          echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > .ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy
        run: ./scripts/deploy.sh github@$SERVER
        env:
          SERVER: "68.183.221.185"
